# -*- coding: utf-8 -*-
"""Projeto_Técnicas_de_Programação_I.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oMLIw_eTIE0oW_XtcAUn-aRLDxCSKHTR

# **Projeto: Técnicas de Programação I**

## **Descrição**

Este notebook contém a descrição do projeto prático do módulo: Técnicas de programação I. Neste projeto aplicaremos as técnicas aprendidas em aula para criarmos uma análise exploratória sobre um conjunto de dados.

## **Objetivo**

Realizar uma análise exploratória de dados utilizando datasets relacionados ao Brasil. Estruture sua análise criando um storytelling: Uma história contada com informações, gráficos, imagens e medidas estatísticas, associando dados a fatos em uma linha do tempo. Você está livre para incluir quantas bases considerar necessário e filtrar as informações mais relevantes para sua história.

## **Dados**

Esta é uma lista de fontes que vocês podem utilizar. Você está livre para utilizar esta e outras fontes de dados, desde que haja uma concordância prévia com o professor.

> ### Fontes de dados sugeridas:

- Covid19br (https://github.com/wcota/covid19br/)
 - Agência Nacional de Petróleo e Gás (https://bit.ly/3hf8rbZ)
 - DataSUS (ftp.datasus.gov.br)*
 - Dados.gov.br (https://bit.ly/3fPA1MO)
 - Kaggle (https://www.kaggle.com/)
 
*Obs: pode ser acessado por um cliente FTP (Ex.: Filezilla)

## **Organização e entregáveis**

O projeto pode ser feito em grupo de até 05 participantes.<br> 
O projeto completo (Notebook, código-fonte, link para fontes, bases e demais artefatos) deve ser publicado no Github.<br>
O projeto completo (Notebook, código-fonte, link para fontes, bases e demais artefatos) deve ser enviado por e-mail (alexlimacavalera@gmail.com) com nome dos participantes e link do repositório no github.<br>

### Critérios de avaliação

A avaliação será feita com base nos artefatos entregues e na sua apresentação.<br> 
A estrutura abaixo lista sugestões do que pode conter no seu trabalho.

- Apresentação da análise
     - Storytelling; 
     - Insights (padrões que descrevam os elementos da base);
     - Descrição do problema;
     - Proposta de solução;
 - Entregáveis
     - Relatório com análise exploratória de dados;
         - Descrição das variáveis (Dados faltantes, tipos de dados, informações relacionadas e fontes);
         - Limpeza da base
     - Análise Univariada e Multivariada
         - Medidas estatísticas;
         - Comparações;
         - Tendências de crescimento ou queda;
     - Gráficos

#### Critérios:

- `Análise` (O nível de exploração dos dados, quantidade de bases e variáveis);
- `Reprodutibilidade` (O código será executado e o resultados precisam ser reproduzidos);
- `Comunicação` (Explique o problema e como a equipe explorou os dados);

#### Deadline

**Apresentação**: 20/01/2022 <br>
**Tempo de apresentação**: A depender da quantidade de grupos. (Aproximadamente de 15 ~ 20 minutos)

---
# Bases utilizadas:

## **Primária**
- ### TIC Indivíduos<br>
A pesquisa TIC Domicílios tem o objetivo de mapear o acesso às TIC (Tecnologias da Informação e Comunicação) nos domicílios urbanos e rurais do país e as suas formas de uso por indivíduos de 10 anos de idade ou mais. Os indicadores gerados pela pesquisa oferecem um cenário do acesso e do uso de TIC do Brasil.
  - Sobre: https://www.cetic.br/pt/pesquisa/domicilios/ <br>
  - Dados: https://www.cetic.br/pt/pesquisa/domicilios/microdados/

---
# Início

## Inicialização dos dados

### Parâmetros iniciais e carregamento dos dados
"""

# Importanto bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# LISTAGEM DAS VARIÁVEIS POR MÓDULO
# OBS: comente a linha da variável para removê-la

# Informações do comicílio
info_domicilio = [
#    'QUEST',            # Número de identificação do questionário
#    'ESTRATO',          # Estrato de seleção
#    'UPA',              # Código do setor censitário
#    'ID_DOMICILIO',     # Número de identificação do domicílio
#    'GRAU_INSTRUCAO_2', # Grau de instrução informado pelo respondente
#    'PEA_2',            # Condição de atividade
    'COD_REGIAO_2',     # Região
    'CLASSE_2015',      # Classe econômica pelo Critério Brasil 2015
    'AREA',             # Área
#    'RENDA_FAMILIAR_2', # Renda familiar em salários mínimos
]

# Informações pessoais
infos_pessoais = [
#    'ID_MORADOR',     # Número de identificação do morador que foi selecionado para responder a pesquisa (id_morador do quadro domiciliar)
#    'PESO',           # Peso do indivíduo
    'SEXO',           # Sexo
    'IDADE',          # Idade do respondente
    'FAIXA_ETARIA',   # Faixa etária
    'GRAU_INSTRUCAO', # Grau de instrução informado pelo respondente
    'PEA',            # Condição de atividade
    'RENDA_PESSOAL',  # Renda pessoal
    'RELIGIAO',       # Religião ou culto
    'RACA',           # Cor ou raça declarada pelo respondente
]

# Módulo C: Uso da Internet
modulo_c = [
    'C1',       # O respondente já usou a Internet?
#    'C2_A',     # O respondente nunca usou a Internet por falta de necessidade?
#    'C2_B',     # O respondente nunca usou a Internet por falta de interesse?
#    'C2_C',     # O respondente nunca usou a Internet por falta de habilidade com o computador?
#    'C2_D',     # O respondente nunca usou a Internet por não ter onde usar?
#    'C2_E',     # O respondente nunca usou a Internet por ser muito caro?
#    'C2_F',     # O respondente nunca usou a Internet por preocupações com segurança ou privacidade?
#    'C2_G',     # O respondente nunca usou a Internet para evitar o contato com conteúdo perigoso?
#    'C2_OUTRO', # O respondente nunca usou a Internet por outro motivo?
#    'C2A',      # E qual desses motivos é o principal?
#    'C3',       # Quando o respondente usou a Internet pela última vez?
#    'C4',       # Em média, com que freqüência o respondente usou a Internet nos últimos 3 meses?
    'C5_A',     # Nos últimos 3 meses, o respondente utilizou a Internet no computador de mesa?
    'C5_B',     # Nos últimos 3 meses, o respondente utilizou a Internet no notebook?
    'C5_C',     # Nos últimos 3 meses, o respondente utilizou a Internet no Tablet?
    'C5_D',     # Nos últimos 3 meses, o respondente utilizou a Internet no telefone celular?
    'C5_E',     # Nos últimos 3 meses, o respondente utilizou a Internet no videogame?
    'C5_F',     # Nos últimos 3 meses, o respondente utilizou a Internet na televisão?
    'C5_OUTRO', # Nos últimos 3 meses, o respondente utilizou a Internet em outro aparelho?
    'C6_A',     # Pensando nos últimos 3 meses, o respondente utilizou a Internet em casa?
    'C6_B',     # Pensando nos últimos 3 meses, o respondente utilizou a Internet no trabalho?
    'C6_C',     # Pensando nos últimos 3 meses, o respondente utilizou a Internet na escola ou estabelecimento de ensino?
    'C6_D',     # Pensando nos últimos 3 meses, o respondente utilizou a Internet na casa de outra pessoa, como por exemplo amigo, vizinho ou familiar?
    'C6_E',     # Pensando nos últimos 3 meses, o respondente utilizou a Internet no centro público de acesso gratuito, como por exemplo telecentro, biblioteca ou entidade comunitária?
    'C6_F',     # Pensando nos últimos 3 meses, o respondente utilizou a Internet no centro público de acesso pago, como por exemplo lanhouse, Cyber Café ou Internet café?
    'C6_G',     # Pensando nos últimos 3 meses, o respondente utilizou a Internet enquanto se desloca, como por exemplo na rua, no ônibus, no metrô, no carro?
#    'C6_OUTRO', # Pensando nos últimos 3 meses, o respondente utilizou a Internet em outro lugar?
    'C6A',      # Em qual desses locais o respondente usou a Internet com mais freqüência?
    'C7_A',     # Nos últimos 3 meses,  o respondente utilizou a Internet para enviar e receber e-mail?
    'C7_B',     # Nos últimos 3 meses,  o respondente utilizou a Internet para enviar mensagens instantâneas (como, por exemplo,  por Facebook, Skype e Whatsapp)?
    'C7_C',     # Nos últimos 3 meses,  o respondente utilizou a Internet para conversar por voz ou vídeo através de programas como Skype ou no Whatsapp?
    'C7_D1',    # Nos últimos 3 meses,  o respondente usou redes sociais, como Facebook, Instagram ou TikTok?
#    'C7_E',     # Nos últimos 3 meses,  o respondente utilizou a Internet para participar de listas de discussão ou fóruns?
#    'C7_F',     # Nos últimos 3 meses,  o respondente utilizou a Internet para usar microblog como, por exemplo, Twitter?
#    'C8_A',     # Nos últimos 3 meses, o respondente utilizou a Internet para procurar informações sobre produtos e serviços?
#    'C8_B',     # Nos últimos 3 meses, o respondente utilizou a Internet para procurar informações relacionadas à saúde ou a serviços de saúde?
#    'C8_C',     # Nos últimos 3 meses, o respondente utilizou a Internet para procurar informações sobre viagens e acomodações?
    'C8_D',     # Nos últimos 3 meses, o respondente utilizou a Internet para procurar emprego ou enviar currículos?
#    'C8_E',     # Nos últimos 3 meses, o respondente utilizou a Internet para procurar informações em sites de enciclopédia virtual como Wikipédia?
#    'C8_F',     # Nos últimos 3 meses, o respondente utilizou a Internet para procurar informações oferecidas por sites de governo?
#    'C8_G',     # Nos últimos 3 meses, o respondente utilizou a Internet para realizar algum serviço público como, por exemplo, emitir documentos pela Internet, preencher e enviar formulários online, ou pagar taxas e impostos pela Internet?
    'C8_H',     # Nos últimos 3 meses, o respondente utilizou a Internet para fazer consultas, pagamentos ou outras transações financeiras?
    'C9_A',     # Nos últimos 3 meses, o respondente utilizou a Internet para jogar on-line?
    'C9_B',     # Nos últimos 3 meses, o respondente utilizou a Internet para ouvir música on-line como por Spotify, por Deezer ou por Youtube?
    'C9_C',     # Nos últimos 3 meses, o respondente utilizou a Internet para assistir vídeos, programas, filmes ou séries em sites como o Youtube ou Netflix?
    'C9_D',     # Nos últimos 3 meses, o respondente utilizou a Internet para ler jornais, revistas ou notícias?
#    'C9_F',     # Nos últimos 3 meses, o respondente utilizou a Internet para ver exposições e museus?
#    'C9_G',     # Nos últimos 3 meses, o respondente utilizou a Internet para ouvir podcasts?
    'C9_E',     # Nos últimos 3 meses, o respondente utilizou a Internet para acompanhar transmissões de áudio ou vídeo em tempo real ou lives pela Internet?
    'C10_A',    # Nos últimos 3 meses, o respondente utilizou a Internet para realizar atividades ou pesquisas escolares?
    'C10_B',    # Nos últimos 3 meses, o respondente utilizou a Internet para fazer cursos à distância?
#    'C10_C',    # Nos últimos 3 meses, o respondente utilizou a Internet para buscar informações sobre cursos de graduação, pós-graduação e de extensão?
    'C10_D',    # Nos últimos 3 meses, o respondente utilizou a Internet para estudar na Internet por conta própria?
#    'C10_E',    # Nos últimos 3 meses, o respondente utilizou a Internet para usar serviço de armazenamento na Internet, como por exemplo Dropbox, Google Drive, Onedrive?
    'C10_F',    # Nos últimos 3 meses, o respondente utilizou a Internet para realizar atividades de trabalho?
#    'C11_A',    # Nos últimos 3 meses, o respondente utilizou a Internet para compartilhar conteúdo na Internet, como textos, imagens, fotos, vídeos ou músicas?
#    'C11_B',    # Nos últimos 3 meses, o respondente utilizou a Internet para criar ou atualizar blogs, páginas na Internet ou websites?
#    'C11_C',    # Nos últimos 3 meses, o respondente utilizou a Internet para postar na Internet textos, imagens, fotos, vídeos ou músicas que o respondente mesmo fez?
#    'C12_A',    # Nos últimos 3 meses, o respondente utilizou a Internet para baixar ou fazer o download de filmes?
#    'C12_B',    # Nos últimos 3 meses, o respondente utilizou a Internet para baixar ou fazer o download de músicas?
#    'C12_C',    # Nos últimos 3 meses, o respondente utilizou a Internet para baixar ou fazer o download de jogos?
#    'C12_D',    # Nos últimos 3 meses, o respondente utilizou a Internet para baixar ou fazer o download de softwares, programas de computador ou aplicativos?
#    'C12_E1',   # Nos últimos 3 meses, o respondente utilizou a Internet para baixar ou fazer o download de livros digitais?
#    'C12_F1',   # Nos últimos 3 meses, o respondente utilizou a Internet para baixar ou fazer o download de séries?
]

# Módulo H: Comércio Eletrônico
modulo_h = [
    'H2', # Nos últimos 12 meses, o respondente comprou ou encomendou produtos ou serviços pela Internet, mesmo que o pagamento não tenha sido feito pela Internet?
]

# Módulo B: Complemento do Uso de Computador
modulo_b = [
#     'B1',   # O respondente já usou um computador de mesa, um notebook ou um tablet?
#     'B2',   # Quando o respondente usou um computador de mesa, um notebook ou um tablet pela última vez?
#     'B4_A', # Nos últimos 3 meses, o respondente usou um computador de mesa, um notebook ou um tablet em casa? 
#     'B4_B', # Nos últimos 3 meses, o respondente usou um computador de mesa, um notebook ou um tablet no trabalho? 
#     'B4_C', # Nos últimos 3 meses, o respondente usou um computador de mesa, um notebook ou um tablet na escola ou estabelecimento de ensino? 
#     'B4_D', # Nos últimos 3 meses, o respondente usou um computador de mesa, um notebook ou um tablet na casa de outra pessoa, como por exemplo amigo, vizinho ou familiar? 
#     'B4_E', # Nos últimos 3 meses, o respondente usou um computador de mesa, um notebook ou um tablet no centro público de acesso gratuito, como por exemplo telecentro, biblioteca ou entidade comunitária? 
#     'B4_F', # Nos últimos 3 meses, o respondente usou um computador de mesa, um notebook ou um tablet no centro público de acesso pago, como por exemplo lanhouse, Cyber Café ou  Internet Café? 
#     'B4_G', # Nos últimos 3 meses, o respondente usou um computador de mesa, um notebook ou um tablet enquanto se desloca, como por exemplo na rua, no ônibus, no metrô ou no carro? 
#     'B4_H', # Nos últimos 3 meses, o respondente usou um computador de mesa, um notebook ou um tablet em algum outro lugar? 
]

# Módulo I: Habilidades com o computador
modulo_i = [
#     'I1_A', # Nos últimos 3 meses, o respondente copiou ou moveu um arquivo ou uma pasta?
#     'I1_B', # Nos últimos 3 meses, o respondente copiou e colou informações em um documento?
#     'I1_C', # Nos últimos 3 meses, o respondente anexou arquivos em e-mails?
#     'I1_D', # Nos últimos 3 meses, o respondente usou uma planilha de cálculo?
#     'I1_E', # Nos últimos 3 meses, o respondente instalou novos equipamentos, como modem, impressora, câmera ou microfone?
#     'I1_F', # Nos últimos 3 meses, o respondente instalou programas de computador ou aplicativo?
#     'I1_G', # Nos últimos 3 meses, o respondente criou apresentações de slides?
#     'I1_H', # Nos últimos 3 meses, o respondente transferiu arquivos entre computador e outros equipamentos ou dispositivos?
#     'I1_I', # Nos últimos 3 meses, o respondente criou programa de computador usando linguagem de programação?
]

# Módulo J: Telefone celular
modulo_j = [
    'J1',             # Nos últimos 3 meses, o respondente usou um telefone celular?
    'J2_A',           # Nos últimos 3 meses, o respondente usou o telefone celular para efetuar e receber chamadas telefônicas?
#    'J2_B',           # Nos últimos 3 meses, o respondente usou o telefone celular para enviar mensagens de texto SMS?
    'J2_C',           # Nos últimos 3 meses, o respondente usou o telefone celular para ouvir músicas?
#    'J2_D',           # Nos últimos 3 meses, o respondente usou o telefone celular para assistir vídeos?
    'J2_E',           # Nos últimos 3 meses, o respondente usou o telefone celular para jogar?
#    'J2_F',           # Nos últimos 3 meses, o respondente usou o telefone celular para tirar fotos?
#    'J2_G',           # Nos últimos 3 meses, o respondente usou o telefone celular para usar mapas, por exemplo o Google Maps?
    'J2_H1',          # Nos últimos 3 meses, o respondente usou o telefone celular para enviar e receber e-mails?
    'J2_I1',          # Nos últimos 3 meses, o respondente usou o telefone celular para acessar redes sociais, como Facebook, Instagram ou TikTok?
#    'J2_J',           # Nos últimos 3 meses, o respondente usou o telefone celular para acessar páginas ou sites?
#    'J2_K',           # Nos últimos 3 meses, o respondente usou o telefone celular para baixar aplicativos?
#    'J2_L',           # Nos últimos 3 meses, o respondente usou o telefone celular para buscar informações, como por exemplo no Google?
#    'J2_M',           # Nos últimos 3 meses, o respondente usou o telefone celular para compartilhar fotos, vídeos ou textos?
    'J2_N',           # Nos últimos 3 meses, o respondente usou o telefone celular para enviar mensagens de texto pela Internet, como por WhatsApp, Skype ou chat do Facebook?
    'J3',             # O respondente usou a Internet pelo telefone celular nos últimos 3 meses?
#    'J3A_A',          # Quando o respondente usou a Internet pelo telefone celular nos últimos 3 meses, utilizou conexão 3g ou 4g?
#    'J3A_B',          # Quando o respondente usou a Internet pelo telefone celular nos últimos 3 meses, utilizou conexão wi-fi?
    'J5',             # O respondente possui telefone celular?
#    'J5_QTD_LINHAS',  # Quantidade de linhas/chips ativos informados pelo respondente.
#    'J6',             # O telefone que o respondente possui é pré ou pós pago?
]

# Módulo TC: TIC Cultura
modulo_tc = [
#    'TC1',      # Nos últimos 3 meses, com que frequência o respondente ouviu música pela Internet? 
#    'TC2',      # Nos últimos 3 meses, o respondente pagou para ouvir música pela Internet?
#    'TC3_A',    # Nos últimos 3 meses, o respondente ouviu pela Internet músicas estrangeiras?
#    'TC3_B',    # Nos últimos 3 meses, o respondente ouviu pela Internet músicas brasileiras?
    'TC4_A',    # Nos últimos 3 meses, o respondentes assistiu filmes pela Internet?
    'TC4_B',    # Nos últimos 3 meses, o respondentes assistiu séries pela Internet?
#    'TC4_C',    # Nos últimos 3 meses, o respondentes assistiu a programas de TV pela Internet?
    'TC4_D',    # Nos últimos 3 meses, o respondentes assistiua a outros vídeos pela Internet, como no Youtube, Facebook ou WhatsApp?
    'TC4B_A',   # Nos últimos 3 meses, o respondente assistiu a vídeos de Notícias pela Internet?
#    'TC4B_B',   # Nos últimos 3 meses, o respondente assistiu a vídeos de Esportes pela Internet?
#    'TC4B_C',   # Nos últimos 3 meses, o respondente assistiu a vídeos de Música, como shows ou vídeo clipes pela Internet?
#    'TC4B_D',   # Nos últimos 3 meses, o respondente assistiu a vídeos de Comédia ou programas humorísticos pela Internet?
    'TC4B_E',   # Nos últimos 3 meses, o respondente assistiu a vídeos de Eventos ou programas religiosos pela Internet?
    'TC4B_F',   # Nos últimos 3 meses, o respondente assistiu a vídeos de Animações ou desenhos animados pela Internet?
#    'TC4B_G',   # Nos últimos 3 meses, o respondente assistiu a vídeos de Pessoas jogando videogame pela Internet?
    'TC4B_H',   # Nos últimos 3 meses, o respondente assistiu a vídeos de Tutoriais ou vídeo aulas pela Internet?
    'TC4B_I',   # Nos últimos 3 meses, o respondente assistiu a vídeos de Influenciadores digitais, como youtubers pela Internet?
#    'TC4B_J',   # Nos últimos 3 meses, o respondente assistiu a vídeos de Outros temas ou assuntos?
    'TC4C_A',   # Nos últimos 3 meses, o respondente assistiu a vídeos, programas, filmes ou séries em sites ou aplicativos de compartilhamento de vídeos, como Youtube ou Vimeo?
    'TC4C_B1',  # Nos últimos 3 meses, o respondente assistiu a vídeos, programas, filmes ou séries em redes sociais, como Facebook, Instagram ou TikTok?
    'TC4C_C',   # Nos últimos 3 meses, o respondente assistiu a vídeos, programas, filmes ou séries em aplicativos de mensagens, como WhatsApp ou Telegram?
    'TC4C_D',   # Nos últimos 3 meses, o respondente assistiu a vídeos, programas, filmes ou séries em serviços por assinatura como Netflix, Globoplay, Minha Sky ou Net Now?
    'TC4C_E',   # Nos últimos 3 meses, o respondente assistiu a vídeos, programas, filmes ou séries em serviços de aluguel ou compra de vídeos, como Google Play  ou iTunes?
    'TC4C_F',   # Nos últimos 3 meses, o respondente assistiu a vídeos, programas, filmes ou séries em serviços de download gratuito de conteúdos, como o 4Shared ou torrent?
#    'TC5_A',    # Nos últimos 3 meses, com que frequência o respondente assistiu a filmes pela Internet?
#    'TC5_B',    # Nos últimos 3 meses, com que frequência o respondente assistiu a séries pela Internet?
    'TC6_A',    # Nos últimos 3 meses, o respondente pagou para assistir a filmes pela Internet?
    'TC6_B',    # Nos últimos 3 meses, o respondente pagou para assistir a séries pela Internet?
#    'TC7_A',    # Nos últimos 3 meses, o respondente assistiu pela Internet a filmes estrangeiros, ou seja, feitos em outros países? 
#    'TC7_B',    # Nos últimos 3 meses, o respondente assistiu pela Internet a filmes brasileiros, ou seja, feitos no Brasil? 
#    'TC8_A',    # Nos últimos 3 meses, o respondente assistiu pela Internet a séries estrangeiras, ou seja, feitas em outros países? 
#    'TC8_B',    # Nos últimos 3 meses, o respondente assistiu pela Internet a séries brasileiras, ou seja, feitas no Brasil? 
    'TC9_A',    # Nos últimos 3 meses, o respondente pagou para baixar ou fazer download de filmes?
    'TC9_B',    # Nos últimos 3 meses, o respondente pagou para baixar ou fazer download de séries?
    'TC9_C',    # Nos últimos 3 meses, o respondente pagou para baixar ou fazer download de músicas?
#    'TC10_A',   # Nos últimos 3 meses, o respondente postou na Internet textos que criou?
#    'TC10_B',   # Nos últimos 3 meses, o respondente postou na Internet imagens ou fotos que criou?
#    'TC10_C',   # Nos últimos 3 meses, o respondente postou na Internet vídeos que criou?
#    'TC10_D',   # Nos últimos 3 meses, o respondente postou na Internet músicas que criou?
#    'TC11_A',   # Nos últimos 3 meses, o respondente criou e postou na Internet fatos ou situações cotidianas?
#    'TC11_B',   # Nos últimos 3 meses, o respondente criou e postou na Internet opinião sobre temas de seu interesse?
#    'TC11_C',   # Nos últimos 3 meses, o respondente ensinou ou deu dicas pela internet para as pessoas sobre coisas que sabia?
    'TC11_D',   # Nos últimos 3 meses, o respondente criou e postou na Internet conteúdo artístico que criou?
    'TC11_E',   # Nos últimos 3 meses, o respondente criou e postou na Internet para se tornar conhecido?
    'TC11_F',   # Nos últimos 3 meses, o respondente criou e postou na Internet para se aproximar de pessoas com interesse comuns?
    'TC11_G',   # Nos últimos 3 meses, o respondente criou e postou na Internet para vender produtos ou serviços?
#    'TC11_H',   # Nos últimos 3 meses, o respondente criou e postou na Internet para divulgar seu trabalho?
#    'TC12',     # Nos últimos 3 meses, o respondente recebeu dinheiro ou outro tipo de pagamento pelo que criou ou postou na internet?
#    'TC13_A',   # O respondente procurou informações na internet para assistir a filmes no cinema? 
#    'TC13_B',   # O respondente procurou informações na internet para assistir a shows de música ou apresentações musicais?
#    'TC13_C',   # O respondente procurou informações na internet para assistir a peças ou espetáculos no teatro?
#    'TC13_D',   # O respondente procurou informações na internet para ir a festas, festivais ou eventos públicos? 
#    'TC13_E',   # O respondente procurou informações na internet para ir a feiras de arte, artesanato ou antiguidades?
#    'TC13_F',   # O respondente procurou informações na internet para ir a museus ou exposições? 
#    'TC13_G',   # O respondente procurou informações na internet para visitar monumentos ou lugares históricos? 
#    'TC13_H',   # O respondente procurou informações na internet para ir a bibliotecas? 
]

# Módulo G: Governo Eletrônico
modulo_g = [
#     'G1_A',     # Nos últimos 12 meses, o respondente usou a Internet para procurar informações ou realizar serviços públicos relacionados a documentos pessoais, como RG, CPF, passaporte, ou carteira de trabalho?
#     'G1_B',     # Nos últimos 12 meses, o respondente usou a Internet para procurar informações ou realizar serviços públicos relacionados a saúde pública, como agendamento de consultas, remédios ou outros serviços do sistema público de saúde?
#     'G1_C',     # Nos últimos 12 meses, o respondente usou a Internet para procurar informações ou realizar serviços públicos relacionados a educação pública, como ENEM, PROUNI, matrícula em escolas ou universidades públicas?
#     'G1_D',     # Nos últimos 12 meses, o respondente usou a Internet para procurar informações ou realizar serviços públicos relacionados a direitos do trabalhador ou previdência social, como INSS, FGTS, seguro-desemprego, auxílio-doença, ou aposentadoria?
#     'G1_E',     # Nos últimos 12 meses, o respondente usou a Internet para procurar informações ou realizar serviços públicos relacionados a impostos e taxas governamentais, como declaração de imposto de renda, IPVA, ou IPTU?
#     'G1_F',     # Nos últimos 12 meses, o respondente usou a Internet para procurar informações ou realizar serviços públicos relacionados a polícia e segurança como boletim de ocorrência, antecedentes criminais ou denúncias?
#     'G1_G',     # Nos últimos 12 meses, o respondente usou a Internet para procurar informações ou realizar serviços públicos relacionados a transporte público ou outros serviços urbanos, como limpeza e conservação de vias, iluminação?
#     'G2_A',     # O respondente realizou serviços referentes a documentos pessoais, como RG, CPF, passaporte, ou carteira de trabalho sem precisar se deslocar até um posto de atendimento para finalizá-lo?
#     'G2_B',     # O respondente realizou serviços referentes a saúde pública, como agendamento de consultas, remédios ou outros serviços do sistema público de saúde sem precisar se deslocar até um posto de atendimento para finalizá-lo?
#     'G2_C',     # O respondente realizou serviços referentes a educação pública, como ENEM, PROUNI, matrícula em escolas ou universidades públicas sem precisar se deslocar até um posto de atendimento para finalizá-lo?
#     'G2_D',     # O respondente realizou serviços referentes a direitos do trabalhador ou previdência social, como INSS, FGTS, seguro-desemprego, auxílio-doença, ou aposentadoria sem precisar se deslocar até um posto de atendimento para finalizá-lo?
#     'G2_E',     # O respondente realizou serviços referentes a impostos e taxas governamentais, como declaração de imposto de renda, IPVA, ou IPTU sem precisar se deslocar até um posto de atendimento para finalizá-lo?
#     'G2_F',     # O respondente realizou serviços referentes a polícia e segurança como boletim de ocorrência, antecedentes criminais ou denúncias sem precisar se deslocar até um posto de atendimento para finalizá-lo?
#     'G2_G',     # O respondente realizou serviços referentes a transporte público ou outros serviços urbanos, como limpeza e conservação de vias, iluminação sem precisar se deslocar até um posto de atendimento para finalizá-lo?
#     'G3_A',     # O respondente não procurou informações ou realizou serviços públicos pela Internet, pois os serviços que precisou não estão disponíveis na Internet?
#     'G3_B',     # O respondente não procurou informações ou realizou serviços públicos pela Internet, pois os serviços que precisou são difíceis de encontrar?
#     'G3_C',     # O respondente não procurou informações ou realizou serviços públicos pela Internet, pois prefere fazer o contato pessoalmente?
#     'G3_D',     # O respondente não procurou informações ou realizou serviços públicos pela Internet, pois dificilmente recebe retorno às solicitações?
#     'G3_E',     # O respondente não procurou informações ou realizou serviços públicos pela Internet, pois tem preocupação com a proteção e a segurança dos dados?
#     'G3_F',     # O respondente não procurou informações ou realizou serviços públicos pela Internet, pois usar a Internet para contato com o governo é complicado?
#     'G3_G',     # O respondente não procurou informações ou realizou serviços públicos pela Internet, pois os serviços que precisa estão disponíveis na Internet, mas não é possível completar a transação?
#     'G3_H',     # O respondente não procurou informações ou realizou serviços públicos pela Internet, por falta de necessidade de buscar informações ou realizar serviços públicos?
#     'G3_OUTRO', # O respondente não procurou informações ou realizou serviços públicos pela Internet por outro motivo?
#     'G4_A',     # Nos últimos 12 meses, o respondente entrou em contato com governo ou instituições públicas por e-mail
#     'G4_B',     # Nos últimos 12 meses, o respondente entrou em contato com governo ou instituições públicas pelo site, como por formulário eletrônico, bate-papo ou chat?
#     'G4_C',     # Nos últimos 12 meses, o respondente entrou em contato com governo ou instituições públicas pelos perfis oficiais em redes sociais, como Facebook ou Twitter?
#     'G4_D',     # Nos últimos 12 meses, o respondente escreveu sugestões ou opiniões em fóruns ou consultas públicas de sites de governo?
#     'G4_E',     # Nos últimos 12 meses, o respondente participou de votações ou enquetes em sites de governo?
]

# Uso de Internet - Módulo de Cobertura
modulo_cob = [
#     'C1_COB_A',     # O Sr. já enviou ou recebeu e-mails?
#     'C1_COB_B',     # O Sr. Já mandou mensagens por WhatsApp ou Telegram?
#     'C1_COB_C1',    # O Sr. Já usou redes sociais como Facebook ou TikTok?
#     'C1_COB_D',     # O Sr. Já buscou informações no Google ou Bing?
#     'C3_COB',       # Quando o Sr. fez essas atividaes pela última vez?
#     'C4_COB',       # Em média, com que frequência o(a) senhor(a) fez essa(s) atividade(s) nos últimos 3 meses? 
#     'C5_COB_A',     # Nos últimos 3 meses o Sr. fez essas atividades no computador de mesa?
#     'C5_COB_B',     # Nos últimos 3 meses o Sr. fez essas atividades no notebook?
#     'C5_COB_C',     # Nos últimos 3 meses o Sr. fez essas atividades no tablet?
#     'C5_COB_D',     # Nos últimos 3 meses o Sr. fez essas atividades no telefone celular?
#     'C5_COB_E',     # Nos últimos 3 meses o Sr. fez essas atividades no videogame?
#     'C5_COB_F',     # Nos últimos 3 meses o Sr. fez essas atividades na televisão?
#     'C5_COB_G',     # Nos últimos 3 meses o Sr. fez essas atividades em outro aparelho?
#     'C6_COB_A',     # Pensando nos últimos 3 meses, o respondente fez essas atividades em casa?
#     'C6_COB_B',     # Pensando nos últimos 3 meses, o respondente fez essas atividades no trabalho?
#     'C6_COB_C',     # Pensando nos últimos 3 meses, o respondente fez essas atividades na escola ou estabelecimento de ensino?
#     'C6_COB_D',     # Pensando nos últimos 3 meses, o respondente fez essas atividades na casa de outra pessoa, como por exemplo amigo, vizinho ou familiar?
#     'C6_COB_E',     # Pensando nos últimos 3 meses, o respondente fez essas atividades no centro público de acesso gratuito, como por exemplo telecentro, biblioteca ou entidade comunitária?
#     'C6_COB_F',     # Pensando nos últimos 3 meses, o respondente fez essas atividades no centro público de acesso pago, como por exemplo lanhouse, Cyber Café ou Internet café?
#     'C6_COB_G',     # Pensando nos últimos 3 meses, o respondente fez essas atividades enquanto se desloca, como por exemplo na rua, no ônibus, no metrô ou no carro?
#     'C6_COB_OUTRO', # Pensando nos últimos 3 meses, o respondente fez essas atividades em outro lugar?
]

# Variáveis Agregadas
variaveis_agregadas = [
    'C5_AGREG',         # Total de usuários de Internet por computador
    'C5_DISPOSITIVOS',  # Dispositivo utilizado pelos usuários de Internet de forma exlcusiva ou simultânea
#    'G1_AGREG',         # Indivíduos que utilizaram governo eletrônico
#    'C8_NAO',           # Não utilizaram a Internet para realizar atividades de interação com autoridades públicas
#    'I1_NENHUM',        # Indicador I1
#    'J5_FAIXAS',        # Faixas de quantidade de linhas de telefone celular
#    'J2_NENHUM',        # Indicador J4
#    'C1_COB_AGREG',     # Não usuários de Internet que declararam ter utilizado alguma aplicação de Internet
#    'C5_COB_AGREG',     # Não usuários de Internet que utilizaram alguma aplicação selecionada
#    'C5_COB_NENHUM',    # Indicador L5
#    'C3J3',             # Indicador ampliado de usuários de Internet
#    'J3_AGREG',         # Indivíduos que usaram a Internet no telefone celular (inclui os usuários de aplicações que necessitam de conexão à Internet)
#    'J3AB',             # Tipo de conexão utilizada de forma exclusiva ou simultânea
#    'G3_NENHUM',        # Indicador G4
#    'C6_COB_NENHUM',    # Indicador L6
]


# DEFINIÇÃO DAS COLUNAS DE INTERESSE
colunas_de_interesse = []\
  +info_domicilio\
  +infos_pessoais\
  +modulo_c\
  +modulo_h\
  +modulo_b\
  +modulo_i\
  +modulo_j\
  +modulo_tc\
  +modulo_g\
  +modulo_cob\
  +variaveis_agregadas

from google.colab import drive
drive.mount('/content/drive')

# Carregando o dataframe
tic2021 = pd.read_csv(filepath_or_buffer='/content/drive/MyDrive/tic_domicilios_2021_individuos_base_de_microdados_v1.0 - tic_domicilios_2021_individuos_base_de_microdados_v1.0.csv', 
                      sep=',',
                      usecols=colunas_de_interesse,
                      #nrows=10,
                      )

"""### Aparência inicial do dataframe"""

# Exibe o dataframe
tic2021

# Lista as colunas do dataframe
tic2021.columns

"""## Limpeza dos dados

### "Tradução" de valores
"""

# Tradução dos valores da coluna 'SEXO'
tic2021['SEXO'].replace(1, 'M', inplace=True)
tic2021['SEXO'].replace(2, 'F', inplace=True)

# # Tradução dos valores da coluna 'RENDA_PESSOAL'
# tic2021['RENDA_PESSOAL'].replace(1, 'R$ 0,01 - R$ 1.100,00', inplace=True)
# tic2021['RENDA_PESSOAL'].replace(2, 'R$ 1.100,01 - R$ 2.200,00', inplace=True)
# tic2021['RENDA_PESSOAL'].replace(3, 'R$ 2.200,01 - R$ 3.300,00', inplace=True)
# tic2021['RENDA_PESSOAL'].replace(4, 'R$ 3.300,01 - R$ 5.500,00', inplace=True)
# tic2021['RENDA_PESSOAL'].replace(5, 'R$ 5.500,01 - R$ 11.000,00', inplace=True)
# tic2021['RENDA_PESSOAL'].replace(6, 'R$ 11.000,01 - R$ 22.000,00', inplace=True)
# tic2021['RENDA_PESSOAL'].replace(7, 'R$ 22.000,01 - R$ 33.000,00', inplace=True)
# tic2021['RENDA_PESSOAL'].replace(8, 'R$ 33.000,01 +', inplace=True)
# tic2021['RENDA_PESSOAL'].replace(9, 'R$ 0', inplace=True)
# tic2021['RENDA_PESSOAL'].replace(97, 'Não sabe', inplace=True)  # Não sabem
# tic2021['RENDA_PESSOAL'].replace(98, np.nan, inplace=True)      # Não responderam

# Tradução dos valores da coluna 'FAIXA_ETARIA'
tic2021['FAIXA_ETARIA'].replace(1, '10-15', inplace=True)
tic2021['FAIXA_ETARIA'].replace(2, '16-24', inplace=True)
tic2021['FAIXA_ETARIA'].replace(3, '25-34', inplace=True)
tic2021['FAIXA_ETARIA'].replace(4, '35-44', inplace=True)
tic2021['FAIXA_ETARIA'].replace(5, '45-59', inplace=True)
tic2021['FAIXA_ETARIA'].replace(6, '60+', inplace=True)

# Tradução dos valores da coluna 'GRAU_INSTRUCAO'
tic2021['GRAU_INSTRUCAO'].replace(1, 'Analfabeto', inplace=True)
tic2021['GRAU_INSTRUCAO'].replace(2, 'Sabe ler/escrever, mas não cursou escola', inplace=True)
tic2021['GRAU_INSTRUCAO'].replace(3, 'Até pré-escola incompleto', inplace=True)
tic2021['GRAU_INSTRUCAO'].replace(4, 'Pré-escola completo', inplace=True)
tic2021['GRAU_INSTRUCAO'].replace(5, '1a - 3a série', inplace=True)
tic2021['GRAU_INSTRUCAO'].replace(6, '4a - 5a série', inplace=True)
tic2021['GRAU_INSTRUCAO'].replace(7, '5a - 7a série', inplace=True)
tic2021['GRAU_INSTRUCAO'].replace(8, '8a série', inplace=True)
tic2021['GRAU_INSTRUCAO'].replace(9, '1o - 2o ano', inplace=True)
tic2021['GRAU_INSTRUCAO'].replace(10, '3o - vestibular', inplace=True)
tic2021['GRAU_INSTRUCAO'].replace(11, 'Superior incompleto', inplace=True)
tic2021['GRAU_INSTRUCAO'].replace(12, 'Superior completo', inplace=True)

# Tradução dos valores da coluna 'RELIGIAO'
tic2021['RELIGIAO'].replace(1, 'Católica', inplace=True)
tic2021['RELIGIAO'].replace(2, 'Luterana/Presbiteriana/Metodista/Batista', inplace=True)
tic2021['RELIGIAO'].replace(3, 'Evangélica (outras)', inplace=True)
tic2021['RELIGIAO'].replace(4, 'Cristã (outras)', inplace=True)
tic2021['RELIGIAO'].replace(5, 'Muçulmana', inplace=True)
tic2021['RELIGIAO'].replace(6, 'Espírita', inplace=True)
tic2021['RELIGIAO'].replace(7, 'Umbanda', inplace=True)
tic2021['RELIGIAO'].replace(8, 'Candomblé', inplace=True)
tic2021['RELIGIAO'].replace(9, 'Judaica', inplace=True)
tic2021['RELIGIAO'].replace(10, 'Hindu', inplace=True)
tic2021['RELIGIAO'].replace(11, 'Budista', inplace=True)
tic2021['RELIGIAO'].replace(12, 'Sem religião', inplace=True)
tic2021['RELIGIAO'].replace(13, 'Agnóstico', inplace=True)
tic2021['RELIGIAO'].replace(14, 'Ateu', inplace=True)
tic2021['RELIGIAO'].replace(16, 'Outras religiões', inplace=True)
tic2021['RELIGIAO'].replace(98, np.nan, inplace=True)

# Tradução dos valores da coluna 'RACA'
tic2021['RACA'].replace(1, 'Branca', inplace=True)
tic2021['RACA'].replace(2, 'Preta', inplace=True)
tic2021['RACA'].replace(3, 'Parda', inplace=True)
tic2021['RACA'].replace(4, 'Amarela', inplace=True)
tic2021['RACA'].replace(5, 'Indígena', inplace=True)
tic2021['RACA'].replace(98, np.nan, inplace=True)

tic2021['COD_REGIAO_2'].replace(1, 'Sudeste', inplace = True)
tic2021['COD_REGIAO_2'].replace(2, 'Nordeste', inplace = True)
tic2021['COD_REGIAO_2'].replace(3, 'Sul', inplace = True)
tic2021['COD_REGIAO_2'].replace(4, 'Norte', inplace = True)
tic2021['COD_REGIAO_2'].replace(1, 'Centro-Oeste', inplace = True)

"""### Aparência do dataframe limpo"""

tic2021

# Dá pra usar o .describe() em colunas específicas.
tic2021['SEXO'].describe()

# Describe das idades
tic2021['IDADE'].describe()

"""## Análises gráficas

## Perfil dos respondentes
"""

tic2021[
    ['COD_REGIAO_2',     # Região
    'CLASSE_2015',      # Classe econômica pelo Critério Brasil 2015
    'AREA',             # Área
    'SEXO',           # Sexo
    'IDADE',          # Idade do respondente
    'FAIXA_ETARIA',   # Faixa etária
    'GRAU_INSTRUCAO', # Grau de instrução informado pelo respondente
    'PEA',            # Condição de atividade
    'RENDA_PESSOAL',  # Renda pessoal
    'RELIGIAO',       # Religião ou culto
    'RACA'            # Cor ou raça declarada pelo respondente
     ]
]

"""

### Sexo dos participantes"""

# Gráfico Sexo dos Participantes
gender = ['Feminino', 'Masculino']
data1 = [tic2021['FAIXA_ETARIA'].value_counts()[1], tic2021['FAIXA_ETARIA'].value_counts()[2]]
fig1 = plt.figure(figsize=(10, 7))
colors1 = ['#ff4545', '#4060ff']
plt.pie(data1, labels = gender, colors=colors1, autopct='%1.1f%%', startangle=90)
plt.axis('equal') 
plt.tight_layout()
plt.show()

"""### Idade dos participantes"""

# Gráfico de faixa etária
fig2 = plt.figure()
ax = fig2.add_axes([0,0,1.8,1.8])
intervals = ['De 10 a 15 anos', 'De 16 a 24 anos', 'De 25 a 34 anos', 'De 35 a 44 anos', 'De 45 a 59 anos', '60 anos ou mais']
frequencies = [tic2021['FAIXA_ETARIA'].value_counts()['10-15'],tic2021['FAIXA_ETARIA'].value_counts()['16-24'],tic2021['FAIXA_ETARIA'].value_counts()['25-34'],
               tic2021['FAIXA_ETARIA'].value_counts()['35-44'],tic2021['FAIXA_ETARIA'].value_counts()['45-59'],tic2021['FAIXA_ETARIA'].value_counts()['60+']]
plt.title('Faixa Etária', fontsize=20)
plt.xlabel('Intervalo de Idade', fontsize=15)
plt.ylabel('Frequência Absoluta', fontsize=15)
plt.tick_params(labelsize=13)
ax.bar(intervals,frequencies, color='purple', alpha=0.7, edgecolor='black')
plt.show()

sns.set(rc={'figure.figsize':(11.7, 8.27)})
sns.boxplot(x="SEXO", y="IDADE", palette=["b", "r"], data=tic2021, width=0.5, fliersize=500)

"""### Renda dos participantes"""

# Gráfico de Renda
fig3 = plt.figure()
ax3 = fig3.add_axes([0,0,3,2])
intervals2 = ['Não sabe', 'Não respondeu', 'Não tem renda' ,'Até R$ 1.100,00', 'De R$ 1.100,01 até\n R$ 2.200,00', 'De R$ 2.200,01 até\n R$ 3.300,00', 'De R$ 3.300,01 até\n R$ 5.500,00', 'De R$ 5.500,01 até\n R$ 11.000,00', 'De R$ 11.000,01 até\n R$ 22.000,00', 'De R$ 22.000,01 até\n R$ 33.000,00', 'Mais de R$ 33.000,00']
frequencies2 = [tic2021['RENDA_PESSOAL'].value_counts()[97], tic2021['RENDA_PESSOAL'].value_counts()[98], tic2021['RENDA_PESSOAL'].value_counts()[9],tic2021['RENDA_PESSOAL'].value_counts()[1],tic2021['RENDA_PESSOAL'].value_counts()[2],tic2021['RENDA_PESSOAL'].value_counts()[3],tic2021['RENDA_PESSOAL'].value_counts()[4],tic2021['RENDA_PESSOAL'].value_counts()[5],tic2021['RENDA_PESSOAL'].value_counts()[6], tic2021['RENDA_PESSOAL'].value_counts()[7], tic2021['RENDA_PESSOAL'].value_counts()[8]]
plt.title('Faixa de Renda', fontsize=20)
plt.xlabel('Intervalo de Renda', fontsize=15)
plt.ylabel('Frequência Absoluta', fontsize=15)
plt.tick_params(labelsize=10)
ax3.bar(intervals2,frequencies2, width=0.8, align='center', color='orange', alpha=0.8, edgecolor='black')
plt.show()

"""### Experiência com a internet"""

data8 = [len(tic2021[tic2021['C1'] == 1]), len(tic2021[tic2021['C1'] == 0])]
chaves = ['Já utilizou a Internet','Nunca utilizou a Internet']
fig8 = plt.figure(figsize=(10, 7))
plt.title('Experiência com a internet', fontsize=20)
plt.pie(data8, labels = chaves,autopct='%.0f%%', startangle=90)
plt.axis('equal') 
plt.tight_layout()
plt.show()

"""## Uso da internet

### Local que mais acessam internet
"""

dic_C6A = {1: 'Casa', 2: 'Trabalho', 3:'Escola', 4: 'Casa de outra pessoa', 5:'Centro público gratuito', 6: 'Centro público pago', 7:'Rua', 8: 'Outros', 97: 'Não sabe', 98: 'Não respondeu', 99: 'Não se aplica'}
count_C6A = tic2021['C6A'].value_counts().rename(dic_C6A)

sns.set(rc={'figure.figsize':(20, 10.13)})
# plt.ylabel('Frequência absoluta', fontsize=15)

plt.xticks(rotation=45)
sns.barplot(x=count_C6A.index, y=count_C6A, color="limegreen")
plt.xlabel('Local', fontsize=15)
plt.ylabel('Quantidade', fontsize=15)

"""### Meios mais usados para conexão de internet"""

values_C5 = {
    "Computador de mesa": len(tic2021[tic2021['C5_A'] == 1]),
    "Notebook": len(tic2021[tic2021['C5_B'] == 1]),
    "Tablet": len(tic2021[tic2021['C5_C'] == 1]),
    "Celular": len(tic2021[tic2021['C5_D'] == 1]),
    "Videogame": len(tic2021[tic2021['C5_E'] == 1]),
    "Televisão": len(tic2021[tic2021['C5_F'] == 1]),
    "Outros": len(tic2021[tic2021['C5_OUTRO'] == 1])
}
plt.xticks(rotation=45)
plt.ylabel('Frequência absoluta', fontsize=15)
# sns.set(rc={'figure.figsize':(20, 14.13)})
sns.barplot(x=list(values_C5.keys()), y=list(values_C5.values()), color="blue")

"""### Dispositivo de uso por faixa etária"""

fig, ax = plt.subplots()
aux = tic2021[tic2021['C5_A'] == 1].groupby('FAIXA_ETARIA').size()
ax = sns.lineplot(x = aux.index, y = aux)
aux = tic2021[tic2021['C5_B'] == 1].groupby('FAIXA_ETARIA').size()
ax = sns.lineplot(x = aux.index, y = aux)
aux = tic2021[tic2021['C5_C'] == 1].groupby('FAIXA_ETARIA').size()
ax = sns.lineplot(x = aux.index, y = aux)
aux = tic2021[tic2021['C5_D'] == 1].groupby('FAIXA_ETARIA').size()
ax = sns.lineplot(x = aux.index, y = aux)
aux = tic2021[tic2021['C5_E'] == 1].groupby('FAIXA_ETARIA').size()
ax = sns.lineplot(x = aux.index, y = aux)
aux = tic2021[tic2021['C5_F'] == 1].groupby('FAIXA_ETARIA').size()
ax = sns.lineplot(x = aux.index, y = aux)
aux = tic2021[tic2021['C5_OUTRO'] == 1].groupby('FAIXA_ETARIA').size()
ax = sns.lineplot(x = aux.index, y = aux)
ax.legend(['Computador de mesa', 'Notebook', 'Tablet', 'Celular', 'Videogame', 'Televisão', 'Outro'], fontsize = 'large')
ax.set_xlabel('Faixa etária')
ax.set_ylabel('Frequência absoluta')

"""### Método de comunicação por faixa etária"""

fig, ax = plt.subplots()
aux = tic2021[tic2021['C7_B'] == 1].groupby('FAIXA_ETARIA').size()*100/tic2021.groupby('FAIXA_ETARIA').size()
ax = sns.lineplot(x = aux.index, y = aux)
aux = tic2021[tic2021['C7_C'] == 1].groupby('FAIXA_ETARIA').size()*100/tic2021.groupby('FAIXA_ETARIA').size()
ax = sns.lineplot(x = aux.index, y = aux)
ax.legend(['Mensagens de texto', 'Conversa por voz ou vídeo'], fontsize = 'large')
ax.set_xlabel('Faixa etária')
ax.set_ylabel('Porcentagem')

"""### Experiência com a internet por região"""

# Pessoas que nunca utilizaram a internet por região
regiao = tic2021.groupby('COD_REGIAO_2').size()
internet = tic2021.loc[tic2021['C1']==0,['COD_REGIAO_2','C1']]
ax = plt.subplots()
ax = sns.barplot(x = regiao.index, y = regiao, color = 'b')
ax = sns.barplot(x= regiao.index, y=internet.groupby('COD_REGIAO_2').size(), color='r', alpha = .8)

plt.ylabel('Frequência absoluta', fontsize=15)
plt.xlabel('Região', fontsize=15)
plt.title('Uso da internet por região', fontsize=20)
plt.show()

